---

charts:
  - name: trino
    chart_file: chart/helm/trino/Chart.yaml
    values_file: chart/helm/trino/new-values.yaml
    image:
      - ghcr.io/netcracker/qubership-trino:${release}
      - ghcr.io/netcracker/qubership-trino-transfer:${release}
