name: Push tag
on:
  workflow_dispatch:
    inputs:
      package_name:
        type: string
        description: "Package name"
        required: true
        default: ''
      docker_file_path:
        type: string
        description: "Path do dockerfile"
        required: true
        default: ''
      context:
        type: string
        description: "Docker build context"
        required: false
        default: .
      tag_name:
        type: string
        description: "Tag name"
        required: true
        default: ''

jobs:
  multiplatform_build:
    strategy:
      fail-fast: false
      matrix:
        component:
          - name: ${{ inputs.package_name }}
            file: ${{ inputs.docker_file_path }}
            context: ${{ inputs.context }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${GITHUB_ACTOR}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          no-cache: true
          context: ${{ matrix.component.context }}
          file: ${{ matrix.component.file }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/netcracker/${{ matrix.component.name }}:${{ inputs.tag_name }}
          provenance: false
      - uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ matrix.component.name }}
          package-type: 'container'
          package-version-ids: ${{ steps.get-ids-for-delete.outputs.ids-for-delete }}
        if: ${{ steps.get-ids-for-delete.outputs.ids-for-delete != '' }}